# Generated by Django 3.0.2 on 2020-03-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='num',
            field=models.IntegerField(default=''),
            preserve_default=False,
        ),
    ]
