# Generated by Django 3.0.2 on 2020-03-26 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20200326_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='val',
        ),
    ]
