# Generated by Django 3.0.2 on 2020-03-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_remove_task_val'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='todo_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
