# Generated by Django 3.0.2 on 2020-03-26 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_task_todo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='todo_id',
        ),
    ]
